### ISSUE TITLE
Isn't that a typo ?

### ISSUE THREAD

**Issue by h4wkmoon** [mischenkovn/velero-exporter#1]
https://github.com/mischenkovn/velero-exporter/blob/fbe9481e11d039d4b4e8150dfb3f6b11c3661df6/servicemonitors_exporter.yaml#L13

**Comment by brunovianna-geru** [comment]
thank you

but, this line command resolved the problem? I looked that you removed this
line. That when applying this manifest of error exactly in that line.

Em sex., 6 de mar. de 2020 às 03:06, mischenkovn <notifications@github.com>
escreveu:

**Comment by mischenkovn** [comment]
thank @brunovianna-geru 
Not, I see yet problem.

**Comment by brunovianna-geru** [comment]
Ok, I undestand.

But, without the command the exporter will work.
All graphics with all metrics?

TKS.

Em sex., 6 de mar. de 2020 às 11:56, mischenkovn <notifications@github.com>
escreveu:

**Comment by mischenkovn** [comment]
We have Deployment "statsd-exporter".
The container "statsd-exporter" read its config file /etc/statsd_mapping.conf and convert data to prometheus format.
The container velero-exporter start script /bin/statsd-get.sh and get data from velero.
You must have Prometheus and Velero installed.
