### ISSUE TITLE
missing metrics for dashboard

### ISSUE THREAD

**Issue by yogeek** [mischenkovn/velero-exporter#2]
Hello and thank you for this project :-)

I just installed you exporter after adapted it for velero 1.3 (I can send you the diffs if you are interested) and I noticed that you only export the metrics `velero_backup_active_total` but not all the metrics needed in the dashboard.
For example : `velero_backup_success_total` , `velero_backup_attempt_total` are used [here](https://github.com/mischenkovn/velero-exporter/blob/master/grafana.json#L203) but are not exported.

Is it normal that the dashboard is not coherent with the exported metrics ?

**Comment by mischenkovn** [comment]
Hi @yogeek !
You can send me diff for velero 1.3 or make Pull request. 
My velero-exporter only adds the missing metrics from the original velero.
You should turn on servicemonitor in velero.

>
     metrics:
      enabled: true
      podAnnotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      scrapeInterval: 30s
      serviceMonitor:
        enabled: true

**Comment by yogeek** [comment]
Hello @mischenkovn and thanks for your help !

Oh you mean that your exporter must be used in complement of the original velero metrics ?
So I must enable both the official velero ServiceMonitor (on which by the way I created an issue [here](https://github.com/vmware-tanzu/velero/issues/2221#issuecomment-620107880) and your ServiceMonitor to have all the metrics needed by your dashboard ?

**Comment by mischenkovn** [comment]
Yes, you should use in complement of the original velero metrics.
I have no purpose to rewrite the original metric. I wanted to add the missing metrics.

I will give a little advise from my side. Don't use the CRDs, the install helm chart. Firstly apply the CRDs, after than install help chart without the CRDs. Or we get problem in upgrade time and can lost information in CRDs.

**Comment by yogeek** [comment]
When you say "don't use the CRDs", you mean the velero CLI ?
On my side, I use the CLI to install the server and never had problems until now with upgrades...
What problems did you have exactly ?

**Comment by mischenkovn** [comment]
I mean then you use helm. In CLI must be all ok.

**Comment by yogeek** [comment]
OK thanks ! 
Maybe you can add a sentence in the README to precise that your exporter is meant to be used in complement of the original velero metrics ?
I close this issue.
